# Override values for production environment
namespace: bns

image:
  tag: latest  # substituir pela tag real no CI/CD

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: axxis-app
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: axxis-app-bff
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:636155393863:certificate/89d6296b-c677-4846-808a-5fea7a5ee620
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: "200-399"
  hosts:
    - host: api.bnscred.com.br
      serviceName: axxis-app-bff

hpa:
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

configmap:
  data:
    BFF_PORT: "8080"
    BACKEND_ADIANTAMENTO_URL: "http://axxis-app-ads/api/v1"
    BACKEND_BNS_URL: "http://axxis-bns-api/api/v1"
    BNS_API_BASE_URL: "http://axxis-bns-api/api/v1"
    BNS_OAUTH_CLIENT_ID: "adiantamento-salario"
