# Deploy: helm upgrade --install axxis-bns-api axxispay/helm-template -f values-prod.yaml --set image.tag=<GIT_SHA>
# Todos os recursos serão criados com o nome: axxis-bns-api
namespace: bns

image:
  repository: 000000000000.dkr.ecr.us-east-1.amazonaws.com/axxis-bns-api
  tag: latest

ingress:
  hosts:
    - host: api.example.com

hpa:
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 1Gi

externalSecret:
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: namespace/app-name

configmap:
  data:
    APP_PORT: "8080"
    DATABASE_URL: "jdbc:postgresql://db-host:5432/db-name"
