{{- if .Values.service.preview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axxispay-helm-template.fullname" . }}-preview
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "axxispay-helm-template.labels" . | nindent 4 }}
spec:
  selector:
    {{- if .Values.preview.enabled }}
    {{- include "axxispay-helm-template.previewSelectorLabels" . | nindent 4 }}
    {{- else }}
    {{- include "axxispay-helm-template.selectorLabels" . | nindent 4 }}
    {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
