apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: axxis-bns-bff
  namespace: argocd
  annotations:
    # argocd-image-updater monitora o ECR e atualiza image.tag automaticamente
    argocd-image-updater.argoproj.io/image-list: axxis-app=636155393863.dkr.ecr.us-east-1.amazonaws.com/axxis-bns-bff
    argocd-image-updater.argoproj.io/axxis-app.update-strategy: digest
    argocd-image-updater.argoproj.io/axxis-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/axxis-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: bns
  source:
    repoURL: git@github.com:axxispay-usa/axxispay-helm-template.git
    targetRevision: main
    path: charts/axxispay
    helm:
      releaseName: axxis-bns-bff
      valueFiles:
        - ../../examples/axxis-bns-bff/values-homolog.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
