# Deploy: helm upgrade --install my-bff axxispay/helm-template -f values-homolog.yaml
# Todos os recursos serão criados com o nome: my-bff
namespace: bns

image:
  repository: 000000000000.dkr.ecr.us-east-1.amazonaws.com/my-bff
  tag: homolog

ingress:
  hosts:
    - host: bff.homolog.example.com
    - host: bff-preview.homolog.example.com
      serviceName: my-app-preview

hpa:
  minReplicas: 1
  maxReplicas: 3

externalSecret:
  refreshInterval: 5m
  dataFrom:
    - extract:
        key: namespace/app-name

configmap:
  data:
    BFF_PORT: "8080"
    BACKEND_ADIANTAMENTO_URL: "http://ads-service/api/v1"
    BACKEND_BNS_URL: "http://backend-service/api/v1"
    BNS_API_BASE_URL: "http://backend-service/api/v1"
    BNS_OAUTH_CLIENT_ID: "adiantamento-salario"
