# Deploy: helm upgrade --install axxis-bns-bff axxispay/helm-template -f values-prod.yaml --set image.tag=<GIT_SHA>
# Todos os recursos serão criados com o nome: axxis-bns-bff
namespace: bns

image:
  repository: 636155393863.dkr.ecr.us-east-1.amazonaws.com/axxis-bns-bff
  tag: latest

ingress:
  hosts:
    - host: bff.bnscred.com.br

hpa:
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

externalSecret:
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: bns/axxis-bns-bff

configmap:
  data:
    BFF_PORT: "8080"
    BACKEND_ADIANTAMENTO_URL: "http://axxis-bns-ads/api/v1"
    BACKEND_BNS_URL: "http://axxis-bns-api/api/v1"
    BNS_API_BASE_URL: "http://axxis-bns-api/api/v1"
    BNS_OAUTH_CLIENT_ID: "adiantamento-salario"
