{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "axxispay-helm-template.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "axxispay-helm-template.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "axxispay-helm-template.fullname" . }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  dataFrom:
    {{- toYaml .Values.externalSecret.dataFrom | nindent 4 }}
{{- end }}
