# Deploy: helm upgrade --install axxis-bns-ads axxispay/helm-template -f values-homolog.yaml
# Todos os recursos serão criados com o nome: axxis-bns-ads
namespace: bns

image:
  repository: 636155393863.dkr.ecr.us-east-1.amazonaws.com/axxis-bns-ads
  tag: homolog

ingress:
  hosts:
    - host: ads.homolog.bnscred.com.br

hpa:
  minReplicas: 1
  maxReplicas: 3

externalSecret:
  refreshInterval: 5m
  dataFrom:
    - extract:
        key: bns/axxis-bns-ads

configmap:
  data:
    APP_PORT: "8080"
    BACKEND_BNS_URL: "http://axxis-bns-api/api/v1"
