# Deploy: helm upgrade --install my-worker axxispay/helm-template -f values-homolog.yaml
# Todos os recursos serão criados com o nome: my-worker
namespace: bns

image:
  repository: 000000000000.dkr.ecr.us-east-1.amazonaws.com/my-worker
  tag: homolog

ingress:
  hosts:
    - host: ads.homolog.example.com

hpa:
  minReplicas: 1
  maxReplicas: 3

externalSecret:
  refreshInterval: 5m
  dataFrom:
    - extract:
        key: namespace/app-name

configmap:
  data:
    APP_PORT: "8080"
    BACKEND_BNS_URL: "http://backend-service/api/v1"
